---
title: "Penguin Flipper Length and Body Mass in Python"
author: "Fang Fang"
date: 2026-09-26
---

Data: [Palmer Penguins](https://allisonhorst.github.io/palmerpenguins/),
Palmer Station Antarctica LTER.
Horst AM, Hill AP, Gorman KB (2020). palmerpenguins: Palmer Archipelago (Antarctica) penguin data. R package version 0.1.0. https://allisonhorst.github.io/palmerpenguins/. doi:10.5281/zenodo.3960218.

In this post, I will compare penguins flipper length and body mass using the Palmer Penguins dataset.

```{python}
from palmerpenguins import load_penguins
import matplotlib.pyplot as plt

penguins = load_penguins()
penguins.head()
```

Before proceeding the analysis, I clean the data first by removing missing values in flipper length and body mass.
For convenience, I also only keep the columns I want to study with.

```{python}
penguins_data = penguins[["species", "flipper_length_mm", "body_mass_g"]].dropna()
```

Next, I calculate the average flipper length and body mass for each species.

```{python}
penguins_data.groupby("species").agg(
    mean_flipper_length_mm=("flipper_length_mm", "mean"),
    mean_body_mass_g=("body_mass_g", "mean"))
```

To study the relation between Flipper Length and Body Mass, I calculate the correlation.

```{python}
penguins_data["flipper_length_mm"].corr(penguins_data["body_mass_g"])
```

After that, I plot Flipper Length and Body Mass into a graph.

```{python}
#| label: fig-python-penguins-flipper-mass
#| fig-cap: "Flipper length and body mass of Palmer penguins."

plt.scatter(penguins_data["flipper_length_mm"],
    penguins_data["body_mass_g"])
plt.xlabel("Flipper length (mm)")
plt.ylabel("Body mass (g)")
plt.show()
```

This plot shows a positive, approximately linear relation between flipper length and body mass. Penguins with longer flippers tend to be heavier.